-- 20260703_fase_b_fk_repoint.sql
-- FASE 1 (Fase B) · re-point FKs auth.users(id) -> user_profiles(id). ONLINE-SAFE.
-- Aplicado por scripts apply-fk-repoint.cjs (por-tabla, lock_timeout 3s + retry, luego VALIDATE).
-- 52 FKs re-apuntados + 1 drop de identidad raíz. ON DELETE preservado.

ALTER TABLE public.user_profiles DROP CONSTRAINT IF EXISTS "user_profiles_id_fkey";

ALTER TABLE public.ai_chat_logs DROP CONSTRAINT IF EXISTS "ai_chat_logs_user_id_fkey";
ALTER TABLE public.ai_chat_logs ADD CONSTRAINT "ai_chat_logs_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.ai_chat_logs VALIDATE CONSTRAINT "ai_chat_logs_user_id_profiles_fkey";
ALTER TABLE public.ai_verification_results DROP CONSTRAINT IF EXISTS "ai_verification_results_verified_by_fkey";
ALTER TABLE public.ai_verification_results ADD CONSTRAINT "ai_verification_results_verified_by_profiles_fkey" FOREIGN KEY (verified_by) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.ai_verification_results VALIDATE CONSTRAINT "ai_verification_results_verified_by_profiles_fkey";
ALTER TABLE public.attribution_touches DROP CONSTRAINT IF EXISTS "attribution_touches_user_id_fkey";
ALTER TABLE public.attribution_touches ADD CONSTRAINT "attribution_touches_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.attribution_touches VALIDATE CONSTRAINT "attribution_touches_user_id_profiles_fkey";
ALTER TABLE public.cancellation_feedback DROP CONSTRAINT IF EXISTS "cancellation_feedback_user_id_fkey";
ALTER TABLE public.cancellation_feedback ADD CONSTRAINT "cancellation_feedback_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.cancellation_feedback VALIDATE CONSTRAINT "cancellation_feedback_user_id_profiles_fkey";
ALTER TABLE public.conversion_events DROP CONSTRAINT IF EXISTS "conversion_events_user_id_fkey";
ALTER TABLE public.conversion_events ADD CONSTRAINT "conversion_events_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.conversion_events VALIDATE CONSTRAINT "conversion_events_user_id_profiles_fkey";
ALTER TABLE public.custom_oposiciones DROP CONSTRAINT IF EXISTS "custom_oposiciones_user_id_fkey";
ALTER TABLE public.custom_oposiciones ADD CONSTRAINT "custom_oposiciones_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.custom_oposiciones VALIDATE CONSTRAINT "custom_oposiciones_user_id_profiles_fkey";
ALTER TABLE public.daily_question_usage DROP CONSTRAINT IF EXISTS "daily_question_usage_user_id_fkey";
ALTER TABLE public.daily_question_usage ADD CONSTRAINT "daily_question_usage_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.daily_question_usage VALIDATE CONSTRAINT "daily_question_usage_user_id_profiles_fkey";
ALTER TABLE public.email_events DROP CONSTRAINT IF EXISTS "email_events_user_id_fkey";
ALTER TABLE public.email_events ADD CONSTRAINT "email_events_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.email_events VALIDATE CONSTRAINT "email_events_user_id_profiles_fkey";
ALTER TABLE public.email_preferences DROP CONSTRAINT IF EXISTS "email_preferences_user_id_fkey";
ALTER TABLE public.email_preferences ADD CONSTRAINT "email_preferences_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.email_preferences VALIDATE CONSTRAINT "email_preferences_user_id_profiles_fkey";
ALTER TABLE public.fraud_alerts DROP CONSTRAINT IF EXISTS "fraud_alerts_reviewed_by_fkey";
ALTER TABLE public.fraud_alerts ADD CONSTRAINT "fraud_alerts_reviewed_by_profiles_fkey" FOREIGN KEY (reviewed_by) REFERENCES public.user_profiles(id) ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.fraud_alerts VALIDATE CONSTRAINT "fraud_alerts_reviewed_by_profiles_fkey";
ALTER TABLE public.fraud_confirmations DROP CONSTRAINT IF EXISTS "fraud_confirmations_action_taken_by_fkey";
ALTER TABLE public.fraud_confirmations ADD CONSTRAINT "fraud_confirmations_action_taken_by_profiles_fkey" FOREIGN KEY (action_taken_by) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.fraud_confirmations VALIDATE CONSTRAINT "fraud_confirmations_action_taken_by_profiles_fkey";
ALTER TABLE public.fraud_watch_list DROP CONSTRAINT IF EXISTS "fraud_watch_list_user_id_fkey";
ALTER TABLE public.fraud_watch_list ADD CONSTRAINT "fraud_watch_list_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.fraud_watch_list VALIDATE CONSTRAINT "fraud_watch_list_user_id_profiles_fkey";
ALTER TABLE public.law_question_first_attempts_pre_outbox DROP CONSTRAINT IF EXISTS "law_question_first_attempts_user_id_fkey";
ALTER TABLE public.law_question_first_attempts_pre_outbox ADD CONSTRAINT "law_question_first_attempts_pre_outbox_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.law_question_first_attempts_pre_outbox VALIDATE CONSTRAINT "law_question_first_attempts_pre_outbox_user_id_profiles_fkey";
ALTER TABLE public.notification_events DROP CONSTRAINT IF EXISTS "notification_events_user_id_fkey";
ALTER TABLE public.notification_events ADD CONSTRAINT "notification_events_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.notification_events VALIDATE CONSTRAINT "notification_events_user_id_profiles_fkey";
ALTER TABLE public.notification_logs DROP CONSTRAINT IF EXISTS "notification_logs_user_id_fkey";
ALTER TABLE public.notification_logs ADD CONSTRAINT "notification_logs_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.notification_logs VALIDATE CONSTRAINT "notification_logs_user_id_profiles_fkey";
ALTER TABLE public.problematic_questions_tracking DROP CONSTRAINT IF EXISTS "problematic_questions_tracking_resolved_by_fkey";
ALTER TABLE public.problematic_questions_tracking ADD CONSTRAINT "problematic_questions_tracking_resolved_by_profiles_fkey" FOREIGN KEY (resolved_by) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.problematic_questions_tracking VALIDATE CONSTRAINT "problematic_questions_tracking_resolved_by_profiles_fkey";
ALTER TABLE public.psychometric_first_attempts DROP CONSTRAINT IF EXISTS "psychometric_first_attempts_user_id_fkey";
ALTER TABLE public.psychometric_first_attempts ADD CONSTRAINT "psychometric_first_attempts_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.psychometric_first_attempts VALIDATE CONSTRAINT "psychometric_first_attempts_user_id_profiles_fkey";
ALTER TABLE public.psychometric_question_disputes DROP CONSTRAINT IF EXISTS "psychometric_question_disputes_admin_user_id_fkey";
ALTER TABLE public.psychometric_question_disputes ADD CONSTRAINT "psychometric_question_disputes_admin_user_id_profiles_fkey" FOREIGN KEY (admin_user_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.psychometric_question_disputes VALIDATE CONSTRAINT "psychometric_question_disputes_admin_user_id_profiles_fkey";
ALTER TABLE public.psychometric_question_disputes DROP CONSTRAINT IF EXISTS "psychometric_question_disputes_user_id_fkey";
ALTER TABLE public.psychometric_question_disputes ADD CONSTRAINT "psychometric_question_disputes_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.psychometric_question_disputes VALIDATE CONSTRAINT "psychometric_question_disputes_user_id_profiles_fkey";
ALTER TABLE public.psychometric_test_answers DROP CONSTRAINT IF EXISTS "psychometric_test_answers_user_id_fkey";
ALTER TABLE public.psychometric_test_answers ADD CONSTRAINT "psychometric_test_answers_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.psychometric_test_answers VALIDATE CONSTRAINT "psychometric_test_answers_user_id_profiles_fkey";
ALTER TABLE public.psychometric_test_sessions DROP CONSTRAINT IF EXISTS "psychometric_test_sessions_user_id_fkey";
ALTER TABLE public.psychometric_test_sessions ADD CONSTRAINT "psychometric_test_sessions_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.psychometric_test_sessions VALIDATE CONSTRAINT "psychometric_test_sessions_user_id_profiles_fkey";
ALTER TABLE public.psychometric_user_question_history DROP CONSTRAINT IF EXISTS "psychometric_user_question_history_user_id_fkey";
ALTER TABLE public.psychometric_user_question_history ADD CONSTRAINT "psychometric_user_question_history_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.psychometric_user_question_history VALIDATE CONSTRAINT "psychometric_user_question_history_user_id_profiles_fkey";
ALTER TABLE public.public_user_profiles DROP CONSTRAINT IF EXISTS "public_user_profiles_id_fkey";
ALTER TABLE public.public_user_profiles ADD CONSTRAINT "public_user_profiles_id_profiles_fkey" FOREIGN KEY (id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.public_user_profiles VALIDATE CONSTRAINT "public_user_profiles_id_profiles_fkey";
ALTER TABLE public.pwa_events DROP CONSTRAINT IF EXISTS "pwa_events_user_id_fkey";
ALTER TABLE public.pwa_events ADD CONSTRAINT "pwa_events_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.pwa_events VALIDATE CONSTRAINT "pwa_events_user_id_profiles_fkey";
ALTER TABLE public.pwa_sessions DROP CONSTRAINT IF EXISTS "pwa_sessions_user_id_fkey";
ALTER TABLE public.pwa_sessions ADD CONSTRAINT "pwa_sessions_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.pwa_sessions VALIDATE CONSTRAINT "pwa_sessions_user_id_profiles_fkey";
ALTER TABLE public.question_first_attempts_pre_outbox DROP CONSTRAINT IF EXISTS "question_first_attempts_user_id_fkey";
ALTER TABLE public.question_first_attempts_pre_outbox ADD CONSTRAINT "question_first_attempts_pre_outbox_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.question_first_attempts_pre_outbox VALIDATE CONSTRAINT "question_first_attempts_pre_outbox_user_id_profiles_fkey";
ALTER TABLE public.session_block_events DROP CONSTRAINT IF EXISTS "session_block_events_user_id_fkey";
ALTER TABLE public.session_block_events ADD CONSTRAINT "session_block_events_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.session_block_events VALIDATE CONSTRAINT "session_block_events_user_id_profiles_fkey";
ALTER TABLE public.share_events DROP CONSTRAINT IF EXISTS "share_events_user_id_fkey";
ALTER TABLE public.share_events ADD CONSTRAINT "share_events_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.share_events VALIDATE CONSTRAINT "share_events_user_id_profiles_fkey";
ALTER TABLE public.spelling_test_answers DROP CONSTRAINT IF EXISTS "spelling_test_answers_user_id_fkey";
ALTER TABLE public.spelling_test_answers ADD CONSTRAINT "spelling_test_answers_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.spelling_test_answers VALIDATE CONSTRAINT "spelling_test_answers_user_id_profiles_fkey";
ALTER TABLE public.spelling_test_sessions DROP CONSTRAINT IF EXISTS "spelling_test_sessions_user_id_fkey";
ALTER TABLE public.spelling_test_sessions ADD CONSTRAINT "spelling_test_sessions_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.spelling_test_sessions VALIDATE CONSTRAINT "spelling_test_sessions_user_id_profiles_fkey";
ALTER TABLE public.telegram_session DROP CONSTRAINT IF EXISTS "telegram_session_user_id_fkey";
ALTER TABLE public.telegram_session ADD CONSTRAINT "telegram_session_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.telegram_session VALIDATE CONSTRAINT "telegram_session_user_id_profiles_fkey";
ALTER TABLE public.upgrade_message_impressions DROP CONSTRAINT IF EXISTS "upgrade_message_impressions_user_id_fkey";
ALTER TABLE public.upgrade_message_impressions ADD CONSTRAINT "upgrade_message_impressions_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE SET NULL ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.upgrade_message_impressions VALIDATE CONSTRAINT "upgrade_message_impressions_user_id_profiles_fkey";
ALTER TABLE public.user_acquisition DROP CONSTRAINT IF EXISTS "user_acquisition_user_id_fkey";
ALTER TABLE public.user_acquisition ADD CONSTRAINT "user_acquisition_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_acquisition VALIDATE CONSTRAINT "user_acquisition_user_id_profiles_fkey";
ALTER TABLE public.user_avatar_settings DROP CONSTRAINT IF EXISTS "user_avatar_settings_user_id_fkey";
ALTER TABLE public.user_avatar_settings ADD CONSTRAINT "user_avatar_settings_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_avatar_settings VALIDATE CONSTRAINT "user_avatar_settings_user_id_profiles_fkey";
ALTER TABLE public.user_devices DROP CONSTRAINT IF EXISTS "user_devices_user_id_fkey";
ALTER TABLE public.user_devices ADD CONSTRAINT "user_devices_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_devices VALIDATE CONSTRAINT "user_devices_user_id_profiles_fkey";
ALTER TABLE public.user_difficulty_metrics DROP CONSTRAINT IF EXISTS "user_difficulty_metrics_user_id_fkey";
ALTER TABLE public.user_difficulty_metrics ADD CONSTRAINT "user_difficulty_metrics_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_difficulty_metrics VALIDATE CONSTRAINT "user_difficulty_metrics_user_id_profiles_fkey";
ALTER TABLE public.user_feedback DROP CONSTRAINT IF EXISTS "user_feedback_admin_user_id_fkey";
ALTER TABLE public.user_feedback ADD CONSTRAINT "user_feedback_admin_user_id_profiles_fkey" FOREIGN KEY (admin_user_id) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_feedback VALIDATE CONSTRAINT "user_feedback_admin_user_id_profiles_fkey";
ALTER TABLE public.user_feedback DROP CONSTRAINT IF EXISTS "user_feedback_user_id_fkey";
ALTER TABLE public.user_feedback ADD CONSTRAINT "user_feedback_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_feedback VALIDATE CONSTRAINT "user_feedback_user_id_profiles_fkey";
ALTER TABLE public.user_inscription_banner_dismissals DROP CONSTRAINT IF EXISTS "user_inscription_banner_dismissals_user_id_fkey";
ALTER TABLE public.user_inscription_banner_dismissals ADD CONSTRAINT "user_inscription_banner_dismissals_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_inscription_banner_dismissals VALIDATE CONSTRAINT "user_inscription_banner_dismissals_user_id_profiles_fkey";
ALTER TABLE public.user_interactions DROP CONSTRAINT IF EXISTS "user_interactions_user_id_fkey";
ALTER TABLE public.user_interactions ADD CONSTRAINT "user_interactions_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_interactions VALIDATE CONSTRAINT "user_interactions_user_id_profiles_fkey";
ALTER TABLE public.user_medals DROP CONSTRAINT IF EXISTS "user_medals_user_id_fkey";
ALTER TABLE public.user_medals ADD CONSTRAINT "user_medals_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_medals VALIDATE CONSTRAINT "user_medals_user_id_profiles_fkey";
ALTER TABLE public.user_message_interactions DROP CONSTRAINT IF EXISTS "user_message_interactions_user_id_fkey";
ALTER TABLE public.user_message_interactions ADD CONSTRAINT "user_message_interactions_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_message_interactions VALIDATE CONSTRAINT "user_message_interactions_user_id_profiles_fkey";
ALTER TABLE public.user_notification_metrics DROP CONSTRAINT IF EXISTS "user_notification_metrics_user_id_fkey";
ALTER TABLE public.user_notification_metrics ADD CONSTRAINT "user_notification_metrics_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_notification_metrics VALIDATE CONSTRAINT "user_notification_metrics_user_id_profiles_fkey";
ALTER TABLE public.user_notification_settings DROP CONSTRAINT IF EXISTS "user_notification_settings_user_id_fkey";
ALTER TABLE public.user_notification_settings ADD CONSTRAINT "user_notification_settings_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_notification_settings VALIDATE CONSTRAINT "user_notification_settings_user_id_profiles_fkey";
ALTER TABLE public.user_oposicion_alerts DROP CONSTRAINT IF EXISTS "user_oposicion_alerts_user_id_fkey";
ALTER TABLE public.user_oposicion_alerts ADD CONSTRAINT "user_oposicion_alerts_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_oposicion_alerts VALIDATE CONSTRAINT "user_oposicion_alerts_user_id_profiles_fkey";
ALTER TABLE public.user_oposiciones_seguidas DROP CONSTRAINT IF EXISTS "user_oposiciones_seguidas_user_id_fkey";
ALTER TABLE public.user_oposiciones_seguidas ADD CONSTRAINT "user_oposiciones_seguidas_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_oposiciones_seguidas VALIDATE CONSTRAINT "user_oposiciones_seguidas_user_id_profiles_fkey";
ALTER TABLE public.user_psychometric_preferences DROP CONSTRAINT IF EXISTS "user_psychometric_preferences_user_id_fkey";
ALTER TABLE public.user_psychometric_preferences ADD CONSTRAINT "user_psychometric_preferences_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_psychometric_preferences VALIDATE CONSTRAINT "user_psychometric_preferences_user_id_profiles_fkey";
ALTER TABLE public.user_streaks DROP CONSTRAINT IF EXISTS "user_streaks_user_id_fkey";
ALTER TABLE public.user_streaks ADD CONSTRAINT "user_streaks_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_streaks VALIDATE CONSTRAINT "user_streaks_user_id_profiles_fkey";
ALTER TABLE public.user_test_sessions DROP CONSTRAINT IF EXISTS "user_test_sessions_user_id_fkey";
ALTER TABLE public.user_test_sessions ADD CONSTRAINT "user_test_sessions_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_test_sessions VALIDATE CONSTRAINT "user_test_sessions_user_id_profiles_fkey";
ALTER TABLE public.user_theme_performance_cache DROP CONSTRAINT IF EXISTS "user_theme_performance_cache_user_id_fkey";
ALTER TABLE public.user_theme_performance_cache ADD CONSTRAINT "user_theme_performance_cache_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_theme_performance_cache VALIDATE CONSTRAINT "user_theme_performance_cache_user_id_profiles_fkey";
ALTER TABLE public.user_video_progress DROP CONSTRAINT IF EXISTS "user_video_progress_user_id_fkey";
ALTER TABLE public.user_video_progress ADD CONSTRAINT "user_video_progress_user_id_profiles_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.user_video_progress VALIDATE CONSTRAINT "user_video_progress_user_id_profiles_fkey";
ALTER TABLE public.verification_queue DROP CONSTRAINT IF EXISTS "verification_queue_created_by_fkey";
ALTER TABLE public.verification_queue ADD CONSTRAINT "verification_queue_created_by_profiles_fkey" FOREIGN KEY (created_by) REFERENCES public.user_profiles(id) ON DELETE NO ACTION ON UPDATE NO ACTION NOT VALID;
ALTER TABLE public.verification_queue VALIDATE CONSTRAINT "verification_queue_created_by_profiles_fkey";
